//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessEntry) DeepCopyInto(out *AccessEntry) {
	*out = *in
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessEntry.
func (in *AccessEntry) DeepCopy() *AccessEntry {
	if in == nil {
		return nil
	}
	out := new(AccessEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIdentitySpec) DeepCopyInto(out *AgentIdentitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIdentitySpec.
func (in *AgentIdentitySpec) DeepCopy() *AgentIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(AgentIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentResourceRequirements) DeepCopyInto(out *AgentResourceRequirements) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentResourceRequirements.
func (in *AgentResourceRequirements) DeepCopy() *AgentResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(AgentResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentResourceValues) DeepCopyInto(out *AgentResourceValues) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentResourceValues.
func (in *AgentResourceValues) DeepCopy() *AgentResourceValues {
	if in == nil {
		return nil
	}
	out := new(AgentResourceValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelPolicySpec) DeepCopyInto(out *ChannelPolicySpec) {
	*out = *in
	if in.GroupAllowExtra != nil {
		in, out := &in.GroupAllowExtra, &out.GroupAllowExtra
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GroupDenyExtra != nil {
		in, out := &in.GroupDenyExtra, &out.GroupDenyExtra
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DmAllowExtra != nil {
		in, out := &in.DmAllowExtra, &out.DmAllowExtra
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DmDenyExtra != nil {
		in, out := &in.DmDenyExtra, &out.DmDenyExtra
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelPolicySpec.
func (in *ChannelPolicySpec) DeepCopy() *ChannelPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ChannelPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelsSpec) DeepCopyInto(out *ChannelsSpec) {
	*out = *in
	if in.DingTalk != nil {
		in, out := &in.DingTalk, &out.DingTalk
		*out = new(DingTalkChannelSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelsSpec.
func (in *ChannelsSpec) DeepCopy() *ChannelsSpec {
	if in == nil {
		return nil
	}
	out := new(ChannelsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialBinding) DeepCopyInto(out *CredentialBinding) {
	*out = *in
	out.CredentialRef = in.CredentialRef
	if in.ToolWhitelist != nil {
		in, out := &in.ToolWhitelist, &out.ToolWhitelist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialBinding.
func (in *CredentialBinding) DeepCopy() *CredentialBinding {
	if in == nil {
		return nil
	}
	out := new(CredentialBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRef) DeepCopyInto(out *CredentialRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRef.
func (in *CredentialRef) DeepCopy() *CredentialRef {
	if in == nil {
		return nil
	}
	out := new(CredentialRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DingTalkChannelSpec) DeepCopyInto(out *DingTalkChannelSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DingTalkChannelSpec.
func (in *DingTalkChannelSpec) DeepCopy() *DingTalkChannelSpec {
	if in == nil {
		return nil
	}
	out := new(DingTalkChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposePort) DeepCopyInto(out *ExposePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposePort.
func (in *ExposePort) DeepCopy() *ExposePort {
	if in == nil {
		return nil
	}
	out := new(ExposePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposedPortStatus) DeepCopyInto(out *ExposedPortStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposedPortStatus.
func (in *ExposedPortStatus) DeepCopy() *ExposedPortStatus {
	if in == nil {
		return nil
	}
	out := new(ExposedPortStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Human) DeepCopyInto(out *Human) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Human.
func (in *Human) DeepCopy() *Human {
	if in == nil {
		return nil
	}
	out := new(Human)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Human) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumanList) DeepCopyInto(out *HumanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Human, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumanList.
func (in *HumanList) DeepCopy() *HumanList {
	if in == nil {
		return nil
	}
	out := new(HumanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HumanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumanSpec) DeepCopyInto(out *HumanSpec) {
	*out = *in
	if in.AccessibleTeams != nil {
		in, out := &in.AccessibleTeams, &out.AccessibleTeams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AccessibleWorkers != nil {
		in, out := &in.AccessibleWorkers, &out.AccessibleWorkers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IdentitySource != nil {
		in, out := &in.IdentitySource, &out.IdentitySource
		*out = new(IdentitySourceSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumanSpec.
func (in *HumanSpec) DeepCopy() *HumanSpec {
	if in == nil {
		return nil
	}
	out := new(HumanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HumanStatus) DeepCopyInto(out *HumanStatus) {
	*out = *in
	if in.Rooms != nil {
		in, out := &in.Rooms, &out.Rooms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HumanStatus.
func (in *HumanStatus) DeepCopy() *HumanStatus {
	if in == nil {
		return nil
	}
	out := new(HumanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentitySourceSpec) DeepCopyInto(out *IdentitySourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentitySourceSpec.
func (in *IdentitySourceSpec) DeepCopy() *IdentitySourceSpec {
	if in == nil {
		return nil
	}
	out := new(IdentitySourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServer) DeepCopyInto(out *MCPServer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServer.
func (in *MCPServer) DeepCopy() *MCPServer {
	if in == nil {
		return nil
	}
	out := new(MCPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Manager) DeepCopyInto(out *Manager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Manager.
func (in *Manager) DeepCopy() *Manager {
	if in == nil {
		return nil
	}
	out := new(Manager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Manager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerConfig) DeepCopyInto(out *ManagerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerConfig.
func (in *ManagerConfig) DeepCopy() *ManagerConfig {
	if in == nil {
		return nil
	}
	out := new(ManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerList) DeepCopyInto(out *ManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Manager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerList.
func (in *ManagerList) DeepCopy() *ManagerList {
	if in == nil {
		return nil
	}
	out := new(ManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerSpec) DeepCopyInto(out *ManagerSpec) {
	*out = *in
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.McpServers != nil {
		in, out := &in.McpServers, &out.McpServers
		*out = make([]MCPServer, len(*in))
		copy(*out, *in)
	}
	out.Config = in.Config
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(AgentResourceRequirements)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.AccessEntries != nil {
		in, out := &in.AccessEntries, &out.AccessEntries
		*out = make([]AccessEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerSpec.
func (in *ManagerSpec) DeepCopy() *ManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerStatus) DeepCopyInto(out *ManagerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerStatus.
func (in *ManagerStatus) DeepCopy() *ManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedSecretRef) DeepCopyInto(out *NamespacedSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedSecretRef.
func (in *NamespacedSecretRef) DeepCopy() *NamespacedSecretRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteSkill) DeepCopyInto(out *RemoteSkill) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteSkill.
func (in *RemoteSkill) DeepCopy() *RemoteSkill {
	if in == nil {
		return nil
	}
	out := new(RemoteSkill)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteSkillSource) DeepCopyInto(out *RemoteSkillSource) {
	*out = *in
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]RemoteSkill, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteSkillSource.
func (in *RemoteSkillSource) DeepCopy() *RemoteSkillSource {
	if in == nil {
		return nil
	}
	out := new(RemoteSkillSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Team) DeepCopyInto(out *Team) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Team.
func (in *Team) DeepCopy() *Team {
	if in == nil {
		return nil
	}
	out := new(Team)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Team) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamAdminSpec) DeepCopyInto(out *TeamAdminSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamAdminSpec.
func (in *TeamAdminSpec) DeepCopy() *TeamAdminSpec {
	if in == nil {
		return nil
	}
	out := new(TeamAdminSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamList) DeepCopyInto(out *TeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Team, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamList.
func (in *TeamList) DeepCopy() *TeamList {
	if in == nil {
		return nil
	}
	out := new(TeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamMemberSpec) DeepCopyInto(out *TeamMemberSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamMemberSpec.
func (in *TeamMemberSpec) DeepCopy() *TeamMemberSpec {
	if in == nil {
		return nil
	}
	out := new(TeamMemberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamMemberStatus) DeepCopyInto(out *TeamMemberStatus) {
	*out = *in
	if in.ExposedPorts != nil {
		in, out := &in.ExposedPorts, &out.ExposedPorts
		*out = make([]ExposedPortStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamMemberStatus.
func (in *TeamMemberStatus) DeepCopy() *TeamMemberStatus {
	if in == nil {
		return nil
	}
	out := new(TeamMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpec) DeepCopyInto(out *TeamSpec) {
	*out = *in
	if in.Admin != nil {
		in, out := &in.Admin, &out.Admin
		*out = new(TeamAdminSpec)
		**out = **in
	}
	if in.HumanMembers != nil {
		in, out := &in.HumanMembers, &out.HumanMembers
		*out = make([]TeamMemberSpec, len(*in))
		copy(*out, *in)
	}
	if in.WorkerMembers != nil {
		in, out := &in.WorkerMembers, &out.WorkerMembers
		*out = make([]TeamWorkerRef, len(*in))
		copy(*out, *in)
	}
	if in.PeerMentions != nil {
		in, out := &in.PeerMentions, &out.PeerMentions
		*out = new(bool)
		**out = **in
	}
	if in.ChannelPolicy != nil {
		in, out := &in.ChannelPolicy, &out.ChannelPolicy
		*out = new(ChannelPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpec.
func (in *TeamSpec) DeepCopy() *TeamSpec {
	if in == nil {
		return nil
	}
	out := new(TeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamStatus) DeepCopyInto(out *TeamStatus) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]TeamMemberStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamStatus.
func (in *TeamStatus) DeepCopy() *TeamStatus {
	if in == nil {
		return nil
	}
	out := new(TeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamWorkerRef) DeepCopyInto(out *TeamWorkerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamWorkerRef.
func (in *TeamWorkerRef) DeepCopy() *TeamWorkerRef {
	if in == nil {
		return nil
	}
	out := new(TeamWorkerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Worker) DeepCopyInto(out *Worker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Worker.
func (in *Worker) DeepCopy() *Worker {
	if in == nil {
		return nil
	}
	out := new(Worker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Worker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerAccessKeyAuthSpec) DeepCopyInto(out *WorkerAccessKeyAuthSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerAccessKeyAuthSpec.
func (in *WorkerAccessKeyAuthSpec) DeepCopy() *WorkerAccessKeyAuthSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerAccessKeyAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerList) DeepCopyInto(out *WorkerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Worker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerList.
func (in *WorkerList) DeepCopy() *WorkerList {
	if in == nil {
		return nil
	}
	out := new(WorkerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerMountSpec) DeepCopyInto(out *WorkerMountSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerMountSpec.
func (in *WorkerMountSpec) DeepCopy() *WorkerMountSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerMountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerOSSAuthSpec) DeepCopyInto(out *WorkerOSSAuthSpec) {
	*out = *in
	if in.RRSA != nil {
		in, out := &in.RRSA, &out.RRSA
		*out = new(WorkerOSSRRSASpec)
		**out = **in
	}
	if in.AccessKey != nil {
		in, out := &in.AccessKey, &out.AccessKey
		*out = new(WorkerAccessKeyAuthSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerOSSAuthSpec.
func (in *WorkerOSSAuthSpec) DeepCopy() *WorkerOSSAuthSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerOSSAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerOSSRRSASpec) DeepCopyInto(out *WorkerOSSRRSASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerOSSRRSASpec.
func (in *WorkerOSSRRSASpec) DeepCopy() *WorkerOSSRRSASpec {
	if in == nil {
		return nil
	}
	out := new(WorkerOSSRRSASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerOSSVolumeSpec) DeepCopyInto(out *WorkerOSSVolumeSpec) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerOSSVolumeSpec.
func (in *WorkerOSSVolumeSpec) DeepCopy() *WorkerOSSVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerOSSVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerResourceSpec) DeepCopyInto(out *WorkerResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerResourceSpec.
func (in *WorkerResourceSpec) DeepCopy() *WorkerResourceSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerSpec) DeepCopyInto(out *WorkerSpec) {
	*out = *in
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemoteSkills != nil {
		in, out := &in.RemoteSkills, &out.RemoteSkills
		*out = make([]RemoteSkillSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.McpServers != nil {
		in, out := &in.McpServers, &out.McpServers
		*out = make([]MCPServer, len(*in))
		copy(*out, *in)
	}
	if in.Expose != nil {
		in, out := &in.Expose, &out.Expose
		*out = make([]ExposePort, len(*in))
		copy(*out, *in)
	}
	if in.ChannelPolicy != nil {
		in, out := &in.ChannelPolicy, &out.ChannelPolicy
		*out = new(ChannelPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = new(ChannelsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(AgentResourceRequirements)
		**out = **in
	}
	if in.ContainerManaged != nil {
		in, out := &in.ContainerManaged, &out.ContainerManaged
		*out = new(bool)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.AccessEntries != nil {
		in, out := &in.AccessEntries, &out.AccessEntries
		*out = make([]AccessEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AgentIdentity != nil {
		in, out := &in.AgentIdentity, &out.AgentIdentity
		*out = new(AgentIdentitySpec)
		**out = **in
	}
	if in.CredentialBindings != nil {
		in, out := &in.CredentialBindings, &out.CredentialBindings
		*out = make([]CredentialBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeployMode != nil {
		in, out := &in.DeployMode, &out.DeployMode
		*out = new(string)
		**out = **in
	}
	if in.ServiceEnabled != nil {
		in, out := &in.ServiceEnabled, &out.ServiceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.BackendRuntime != nil {
		in, out := &in.BackendRuntime, &out.BackendRuntime
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]WorkerVolumeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Mounts != nil {
		in, out := &in.Mounts, &out.Mounts
		*out = make([]WorkerMountSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerSpec.
func (in *WorkerSpec) DeepCopy() *WorkerSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerStatus) DeepCopyInto(out *WorkerStatus) {
	*out = *in
	if in.ExposedPorts != nil {
		in, out := &in.ExposedPorts, &out.ExposedPorts
		*out = make([]ExposedPortStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerStatus.
func (in *WorkerStatus) DeepCopy() *WorkerStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerVolumeSpec) DeepCopyInto(out *WorkerVolumeSpec) {
	*out = *in
	if in.OSS != nil {
		in, out := &in.OSS, &out.OSS
		*out = new(WorkerOSSVolumeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerVolumeSpec.
func (in *WorkerVolumeSpec) DeepCopy() *WorkerVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerVolumeSpec)
	in.DeepCopyInto(out)
	return out
}
