#!/usr/bin/env bash
# Read-only evidence capture for a native AgentTeams Hero run.
# This utility never sends Matrix messages or mutates AgentTeams resources.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  testweaver-native-hero-capture.sh <start|snapshot|stop> \
    --run-id ID --campaign-id ID --trace-id ID --evidence-dir DIR \
    --agt-container NAME --team NAME --team NAME --human-allowlist FILE \
    [--pg-container NAME|NONE] [--pg-user USER] [--pg-db DB]

The Human allowlist is a protected, newline-delimited list of exact Matrix user IDs.
Only its SHA-256 is copied into evidence. Missing runtime facts are NOT_OBSERVED.
EOF
}

die() { printf 'error: %s\n' "$*" >&2; exit 2; }
note_missing() { printf '%s\t%s\n' "$1" "${2:-NOT_OBSERVED}" >>"$SNAPSHOT_DIR/not-observed.tsv"; }
safe_name() { printf '%s' "$1" | tr -c 'A-Za-z0-9._-' '_'; }
sha_file() { sha256sum "$1" | awk '{print $1}'; }
utc_now() { date -u +%Y-%m-%dT%H:%M:%SZ; }
utc_stamp() { date -u +%Y%m%dT%H%M%S%NZ; }
json_array() { jq -s '.'; }

COMMAND="${1:-}"
[[ "$COMMAND" =~ ^(start|snapshot|stop)$ ]] || { usage >&2; exit 2; }
shift

RUN_ID=''
CAMPAIGN_ID=''
TRACE_ID=''
EVIDENCE_DIR=''
AGT_CONTAINER=''
HUMAN_ALLOWLIST=''
PG_CONTAINER=NONE
PG_USER=testweaver
PG_DB=testweaver
TEAMS=()
while (($#)); do
  case "$1" in
    --run-id) RUN_ID="${2:-}"; shift 2 ;;
    --campaign-id) CAMPAIGN_ID="${2:-}"; shift 2 ;;
    --trace-id) TRACE_ID="${2:-}"; shift 2 ;;
    --evidence-dir) EVIDENCE_DIR="${2:-}"; shift 2 ;;
    --agt-container) AGT_CONTAINER="${2:-}"; shift 2 ;;
    --team) TEAMS+=("${2:-}"); shift 2 ;;
    --human-allowlist) HUMAN_ALLOWLIST="${2:-}"; shift 2 ;;
    --pg-container) PG_CONTAINER="${2:-}"; shift 2 ;;
    --pg-user) PG_USER="${2:-}"; shift 2 ;;
    --pg-db) PG_DB="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

for value in RUN_ID CAMPAIGN_ID TRACE_ID AGT_CONTAINER; do
  [[ -n "${!value}" ]] || die "--$(printf '%s' "$value" | tr 'A-Z_' 'a-z-') is required"
done
[[ "$RUN_ID" =~ ^[A-Za-z0-9._:@/-]+$ ]] || die "unsafe run id"
[[ "$CAMPAIGN_ID" =~ ^[A-Za-z0-9._:@/-]+$ ]] || die "unsafe campaign id"
[[ "$TRACE_ID" =~ ^[A-Za-z0-9._:@/-]+$ ]] || die "unsafe trace id"
[[ -n "$EVIDENCE_DIR" ]] || die "--evidence-dir is required"
[[ ${#TEAMS[@]} -eq 2 ]] || die "exactly two --team values are required"
[[ "${TEAMS[0]}" != "${TEAMS[1]}" ]] || die "the two teams must differ"
[[ -f "$HUMAN_ALLOWLIST" ]] || die "--human-allowlist must name a protected file"
[[ ! -L "$HUMAN_ALLOWLIST" ]] || die "human allowlist must not be a symlink"
allow_mode=$(stat -c '%a' "$HUMAN_ALLOWLIST")
(( (8#$allow_mode & 077) == 0 )) || die "human allowlist must not be group/world accessible"
for bin in docker jq sha256sum perl python3 pkill; do command -v "$bin" >/dev/null || die "$bin is required"; done

EVIDENCE_DIR=$(realpath -m "$EVIDENCE_DIR")
STATE_DIR="$EVIDENCE_DIR/.state"
CONFIG="$STATE_DIR/config"
umask 077

redact_stream() {
  perl -pe '
    s{((?:Authorization:\s*Bearer|Bearer)\s+)[^\s,;]+}{${1}[REDACTED]}ig;
    s{((?:x[-_]?(?:api[-_]?key|auth[-_]?token)|api[_-]?key|token|password|secret|client[_-]?secret|access[_-]?key|gateway[_-]?key|matrix[_-]?token|registration[_-]?token|license[_-]?key)\s*[=:]\s*)(?:"[^"]*"|'"'"'[^'"'"']*'"'"'|[^\s,;]+)}{${1}[REDACTED]}ig;
    s{((?:AGENTTEAMS|NACOS|SKILLS)_[A-Z0-9_]*(?:TOKEN|PASSWORD|SECRET|KEY|COOKIE)[A-Z0-9_]*\s*[=:]\s*)(?:"[^"]*"|'"'"'[^'"'"']*'"'"'|[^\s,;]+)}{${1}[REDACTED]}ig;
    s{((?:https?|nacos)://)[^/\s:@]+:[^/\s@]+@}{${1}[REDACTED]@}ig;
  '
}

write_config() {
  mkdir -p "$STATE_DIR"
  {
    printf 'RUN_ID=%q\n' "$RUN_ID"
    printf 'CAMPAIGN_ID=%q\n' "$CAMPAIGN_ID"
    printf 'TRACE_ID=%q\n' "$TRACE_ID"
    printf 'AGT_CONTAINER=%q\n' "$AGT_CONTAINER"
    printf 'TEAM_ONE=%q\n' "${TEAMS[0]}"
    printf 'TEAM_TWO=%q\n' "${TEAMS[1]}"
    printf 'HUMAN_ALLOWLIST=%q\n' "$HUMAN_ALLOWLIST"
    printf 'HUMAN_ALLOWLIST_SHA256=%q\n' "$(sha_file "$HUMAN_ALLOWLIST")"
    printf 'PG_CONTAINER=%q\n' "$PG_CONTAINER"
    printf 'PG_USER=%q\n' "$PG_USER"
    printf 'PG_DB=%q\n' "$PG_DB"
    printf 'BOUNDARY_UTC=%q\n' "$(utc_now)"
    printf 'BOUNDARY_MS=%q\n' "$(( $(date -u +%s) * 1000 ))"
  } >"$CONFIG"
}

load_config() {
  [[ -f "$CONFIG" ]] || die "capture has not been started"
  [[ "$(stat -c '%u:%a' "$CONFIG")" == "$(id -u):600" ]] || die "capture config ownership or mode is unsafe"
  local expected_run=$RUN_ID expected_campaign=$CAMPAIGN_ID expected_trace=$TRACE_ID
  local expected_agt=$AGT_CONTAINER expected_t1=${TEAMS[0]} expected_t2=${TEAMS[1]}
  # Config is generated by this script, mode 0600, and contains no credentials.
  # shellcheck disable=SC1090
  source "$CONFIG"
  [[ "$expected_run" == "$RUN_ID" && "$expected_campaign" == "$CAMPAIGN_ID" ]] || die "capture identity mismatch"
  [[ "$expected_trace" == "$TRACE_ID" && "$expected_agt" == "$AGT_CONTAINER" ]] || die "capture identity mismatch"
  [[ "$expected_t1" == "$TEAM_ONE" && "$expected_t2" == "$TEAM_TWO" ]] || die "team selection mismatch"
  [[ "$HUMAN_ALLOWLIST_SHA256" == "$(sha_file "$HUMAN_ALLOWLIST")" ]] || die "human allowlist changed during capture"
}

agt_json() {
  local resource=$1 output=$2
  if ! docker exec "$AGT_CONTAINER" agt get "$resource" -o json >"$output.tmp" 2>/dev/null; then
    rm -f "$output.tmp"; return 1
  fi
  sha_file "$output.tmp" >"$output.raw.sha256"
  jq -S '.' "$output.tmp" >"$output" && rm -f "$output.tmp"
}

build_roster() {
  local managers=$1 teams=$2 workers=$3 output=$4
  jq -n \
    --slurpfile m "$managers" --slurpfile t "$teams" --slurpfile w "$workers" \
    --arg t1 "${TEAMS[0]}" --arg t2 "${TEAMS[1]}" '
      ($m[0].managers // []) as $managers |
      ($t[0].teams // [] | map(select((.name // .teamName) == $t1 or (.name // .teamName) == $t2))) as $teams |
      ($w[0].workers // []) as $workers |
      {managers: $managers,
       teams: $teams,
       workers: [$workers[] | select(.name as $n | any($teams[]; (.leaderName == $n) or ((.workerNames // []) | index($n))))],
       actors: (([$managers[] | {name:(.name // "manager"), kind:"manager", matrix_user_id:(.matrixUserID // null), runtime:(.runtime // null), provider:(.provider // null), model:(.model // null)}] +
                 [$teams[] as $team | ([{name:$team.leaderName, kind:"leader", team:($team.name // $team.teamName)}] + [($team.workerNames // [])[] | {name:.,kind:"worker",team:($team.name // $team.teamName)}])[] |
                    . as $a | ($workers[] | select(.name == $a.name)) as $w |
                    $a + {matrix_user_id:($w.matrixUserID // null),runtime:($w.runtime // null),provider:($w.provider // null),model:($w.model // null)}]) |
                unique_by(.name))}' >"$output"
  [[ $(jq '.teams | length' "$output") -eq 2 ]] || return 1
}

container_actor_name() {
  local container=$1
  docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' "$container" 2>/dev/null |
    awk -F= '$1=="AGENTTEAMS_WORKER_NAME" || $1=="AGENTTEAMS_MANAGER_NAME" {print $2; exit}'
}

resolve_containers() {
  local roster=$1 output=$2
  : >"$output"
  while IFS= read -r container; do
    [[ -n "$container" ]] || continue
    actor=$(container_actor_name "$container" || true)
    if [[ -n "$actor" ]] && jq -e --arg n "$actor" '.actors[] | select(.name==$n)' "$roster" >/dev/null; then
      printf '%s\t%s\n' "$actor" "$container" >>"$output"
    fi
  done < <(docker ps --format '{{.Names}}')
}

ensure_log_followers() {
  local containers=$1
  mkdir -p "$EVIDENCE_DIR/logs" "$STATE_DIR"
  touch "$STATE_DIR/collectors.tsv"
  while IFS=$'\t' read -r actor container; do
    [[ -n "$actor" && -n "$container" ]] || continue
    if awk -F '\t' -v c="$container" '$2==c {found=1} END {exit !found}' "$STATE_DIR/collectors.tsv"; then continue; fi
    log="$EVIDENCE_DIR/logs/$(safe_name "$actor")--$(safe_name "$container").log"
    (
      set +e
      docker logs --follow --timestamps --since "$BOUNDARY_UTC" "$container" 2>&1 | redact_stream >>"$log"
    ) &
    pid=$!
    printf '%s\t%s\t%s\t%s\n' "$pid" "$container" "$actor" "$log" >>"$STATE_DIR/collectors.tsv"
  done <"$containers"
}

matrix_get() {
  local container=$1 token_var=$2 path=$3 body=$4 hash=$5
  # The token is expanded only inside the actor container and is never printed.
  if ! docker exec "$container" sh -c '
      token_var=$1; path=$2
      eval "token=\${$token_var:-}"
      [ -n "$token" ] || exit 41
      base=${AGENTTEAMS_MATRIX_URL:-${MATRIX_URL:-}}
      [ -n "$base" ] || exit 42
      curl -fsS -H "Authorization: Bearer $token" "${base%/}${path}"
    ' sh "$token_var" "$path" >"$body.raw" 2>/dev/null; then
    rm -f "$body.raw"; return 1
  fi
  sha_file "$body.raw" >"$hash"
  redact_stream <"$body.raw" >"$body"
  rm -f "$body.raw"
  jq -e . "$body" >/dev/null 2>&1
}

uri_component() { jq -rn --arg value "$1" '$value|@uri'; }

capture_matrix_actor() {
  local actor=$1 kind=$2 container=$3 matrix_id=$4 out=$5
  local token_var=AGENTTEAMS_WORKER_MATRIX_TOKEN
  [[ "$kind" == manager ]] && token_var=AGENTTEAMS_MANAGER_MATRIX_TOKEN
  mkdir -p "$out/events"
  if matrix_get "$container" "$token_var" '/_matrix/client/v3/account/whoami' "$out/whoami.json" "$out/whoami.raw.sha256"; then
    whoami=$(jq -r '.user_id // "NOT_OBSERVED"' "$out/whoami.json")
    if [[ "$whoami" != "$matrix_id" ]]; then note_missing "matrix.identity_mismatch.$actor" "$whoami"; fi
  else
    note_missing "matrix.whoami.$actor"
  fi
  if ! matrix_get "$container" "$token_var" '/_matrix/client/v3/joined_rooms' "$out/joined_rooms.json" "$out/joined_rooms.raw.sha256"; then
    note_missing "matrix.joined_rooms.$actor"; return
  fi
  : >"$out/event-index.jsonl"
  while IFS= read -r room; do
    room_uri=$(uri_component "$room")
    room_key=$(safe_name "$room")
    if ! matrix_get "$container" "$token_var" "/_matrix/client/v3/rooms/$room_uri/messages?dir=b&limit=100" "$out/messages-$room_key.json" "$out/messages-$room_key.raw.sha256"; then
      note_missing "matrix.messages.$actor.$room"; continue
    fi
    while IFS=$'\t' read -r event_id _sender origin_ts; do
      [[ -n "$event_id" ]] || continue
      event_uri=$(uri_component "$event_id")
      event_key=$(safe_name "$event_id")
      exact="$out/events/$event_key.json"
      raw_hash_file="$out/events/$event_key.raw.sha256"
      if ! matrix_get "$container" "$token_var" "/_matrix/client/v3/rooms/$room_uri/event/$event_uri" "$exact" "$raw_hash_file"; then
        note_missing "matrix.exact_event.$actor.$event_id"; continue
      fi
      raw_hash=$(cat "$raw_hash_file")
      exact_sender=$(jq -r '.sender // "NOT_OBSERVED"' "$exact")
      exact_room=$(jq -r --arg fallback "$room" '.room_id // $fallback' "$exact")
      binding=UNBOUND
      if [[ "$exact_sender" == "$matrix_id" ]]; then binding=ACTOR_EXACT
      elif grep -Fqx -- "$exact_sender" "$HUMAN_ALLOWLIST"; then
        binding=HUMAN_ALLOWLIST_EXACT
        human_uri=$(uri_component "$exact_sender")
        human_key=$(safe_name "$exact_sender")
        if ! matrix_get "$container" "$token_var" "/_matrix/client/v3/profile/$human_uri" "$out/events/$human_key.profile.json" "$out/events/$human_key.profile.raw.sha256"; then
          note_missing "matrix.human_profile.$exact_sender"
        fi
      fi
      jq -nc --arg actor "$actor" --arg actor_matrix_id "$matrix_id" --arg container "$container" \
        --arg room_id "$exact_room" --arg event_id "$event_id" --arg sender "$exact_sender" \
        --arg binding "$binding" --arg source_ref "${exact#"$EVIDENCE_DIR"/}" --arg raw_sha256 "$raw_hash" \
        --arg run_id "$RUN_ID" --arg campaign_id "$CAMPAIGN_ID" --arg trace_id "$TRACE_ID" \
        --argjson origin_server_ts "${origin_ts:-0}" \
        '{actor:$actor,actor_matrix_id:$actor_matrix_id,container:$container,room_id:$room_id,event_id:$event_id,
          sender:$sender,identity_binding:$binding,origin_server_ts:$origin_server_ts,
          authority_scope:{campaign_id:$campaign_id,run_id:$run_id,trace_id:$trace_id},
          immutable_source:{ref:$source_ref,raw_bytes_sha256:$raw_sha256}}' >>"$out/event-index.jsonl"
    done < <(jq -r --argjson boundary "$BOUNDARY_MS" '(.chunk // [])[] | select((.origin_server_ts // 0) >= $boundary) | [.event_id,.sender,(.origin_server_ts|tostring)] | @tsv' "$out/messages-$room_key.json")
  done < <(jq -r '.joined_rooms[]?' "$out/joined_rooms.json")
}

capture_container() {
  local actor=$1 container=$2 out=$3
  if ! docker inspect "$container" | jq -S '.[0] | {
      container_name:(.Name|ltrimstr("/")), container_id:.Id, image:.Config.Image, image_id:.Image,
      restart_count:.RestartCount, state:.State.Status, started_at:.State.StartedAt,
      health:(.State.Health.Status // "NOT_OBSERVED")}' >"$out" 2>/dev/null; then
    printf '{"status":"NOT_OBSERVED"}\n' >"$out"; note_missing "container.$actor"
  fi
}

capture_skills() {
  local actor=$1 container=$2 out=$3
  mkdir -p "$out"
  if docker exec "$container" sh -c 'curl -fsS http://127.0.0.1:8088/api/agents/default/skills' 2>/dev/null |
      jq -S '[.skills[]? | {name,enabled}]' >"$out/list.json"; then :; else
    printf '{"status":"NOT_OBSERVED"}\n' >"$out/list.json"; note_missing "skills.list.$actor"
  fi
  if ! docker exec "$container" sh -c '
      find /root/agentteams-fs /root/manager-workspace -type f -path "*/skills/*/SKILL.md" -print0 2>/dev/null |
      sort -z | xargs -0 -r sha256sum
    ' >"$out/hashes.txt" 2>/dev/null; then
    printf 'NOT_OBSERVED\n' >"$out/hashes.txt"; note_missing "skills.hash.$actor"
  fi
}

capture_sessions() {
  local actor=$1 kind=$2 container=$3 out=$4
  mkdir -p "$out"
  local find_cmd
  if [[ "$kind" == manager ]]; then
    # Expanded by the actor-container shell, not this process.
    # shellcheck disable=SC2016
    find_cmd='find /root/manager-workspace/.openclaw/agents/main/sessions -maxdepth 1 -type f -name "*.jsonl" -newermt "$CAPTURE_BOUNDARY" -print 2>/dev/null'
  else
    # shellcheck disable=SC2016
    find_cmd='find "/root/agentteams-fs/agents/$ACTOR_NAME" -type f \( -path "*/sessions/agentteams_matrix/*.json" -o -name "*.jsonl" \) -newermt "$CAPTURE_BOUNDARY" -print 2>/dev/null'
  fi
  if ! docker exec -e CAPTURE_BOUNDARY="$BOUNDARY_UTC" -e ACTOR_NAME="$actor" "$container" sh -c "$find_cmd" >"$out/files.txt" 2>/dev/null; then
    printf 'NOT_OBSERVED\n' >"$out/files.txt"; note_missing "session.files.$actor"; return
  fi
  : >"$out/readback.jsonl"
  while IFS= read -r path; do
    [[ -n "$path" ]] || continue
    file_hash=$(docker exec "$container" sha256sum "$path" 2>/dev/null | awk '{print $1}' || true)
    [[ -n "$file_hash" ]] || { note_missing "session.hash.$actor"; continue; }
    # Only provider metadata leaves the container; prompts, outputs and tool arguments never do.
    if ! docker exec "$container" sh -c 'cat "$1"' sh "$path" 2>/dev/null |
      python3 -c 'import hashlib,json,sys
run_id,campaign_id,trace_id=sys.argv[1:4]
for raw in sys.stdin.buffer:
 try:
  value=json.loads(raw)
 except Exception:
  continue
 msg=value.get("message", value)
 if not isinstance(msg,dict): continue
 role=msg.get("role")
 if role not in ("user","assistant"): continue
 usage=msg.get("usage") if isinstance(msg.get("usage"),dict) else None
 text=raw.decode("utf-8","replace")
 safe={"record_hash":hashlib.sha256(raw).hexdigest(),"id":value.get("id"),"timestamp":value.get("timestamp"),"role":role,"provider":msg.get("provider"),"model":msg.get("model"),"usage":usage,"latency_ms":msg.get("durationMs") or value.get("durationMs"),"scope_mentions":{"run_id":run_id in text,"campaign_id":campaign_id in text,"trace_id":trace_id in text}}
 print(json.dumps(safe,separators=(",",":"),sort_keys=True))' "$RUN_ID" "$CAMPAIGN_ID" "$TRACE_ID" |
      jq -c --arg actor "$actor" --arg container "$container" --arg session_file_sha256 "$file_hash" --arg session_ref "$path" \
        '. + {actor:$actor,container:$container,session_file_sha256:$session_file_sha256,session_ref:$session_ref}' >>"$out/readback.jsonl"; then
      note_missing "session.readback.$actor"
    fi
  done <"$out/files.txt"
  if ! grep -q '"role":"assistant"' "$out/readback.jsonl"; then note_missing "manager_choice.provider_metadata.$actor"; fi
}

capture_shared_files() {
  local roster=$1 containers=$2 out=$3
  mkdir -p "$out"
  : >"$out/task-artifacts.jsonl"
  : >"$out/task-metadata.jsonl"
  for team in "${TEAMS[@]}"; do
    leader=$(jq -r --arg team "$team" '.teams[] | select((.name // .teamName)==$team) | .leaderName' "$roster")
    container=$(awk -F '\t' -v a="$leader" '$1==a {print $2; exit}' "$containers")
    [[ -n "$container" ]] || { note_missing "shared_fs.$team"; continue; }
    paths="$out/$(safe_name "$team")-paths.txt"
    if ! docker exec -e TEAM_NAME="$team" -e CAPTURE_BOUNDARY="$BOUNDARY_UTC" "$container" sh -c '
      root="/root/agentteams-fs/teams/$TEAM_NAME/shared"
      find "$root/projects" "$root/tasks" -type f -newermt "$CAPTURE_BOUNDARY" -print 2>/dev/null
    ' >"$paths" 2>/dev/null; then
      note_missing "shared_fs.$team"; continue
    fi
    while IFS= read -r path; do
      [[ -n "$path" ]] || continue
      digest=$(docker exec "$container" sha256sum "$path" 2>/dev/null | awk '{print $1}' || true)
      [[ -n "$digest" ]] || continue
      kind=metadata
      [[ "$path" == */result.md ]] && kind=result
      jq -nc --arg team "$team" --arg leader "$leader" --arg container "$container" --arg kind "$kind" \
        --arg source_ref "$path" --arg raw_sha256 "$digest" \
        '{team:$team,leader:$leader,container:$container,kind:$kind,source_ref:$source_ref,raw_bytes_sha256:$raw_sha256}' >>"$out/task-artifacts.jsonl"
      if [[ "$path" == */meta.json ]]; then
        docker exec "$container" sh -c 'cat "$1"' sh "$path" 2>/dev/null |
          jq -c --arg team "$team" --arg source_ref "$path" --arg raw_sha256 "$digest" '
            {team:$team,source_ref:$source_ref,raw_bytes_sha256:$raw_sha256,
             task_id:(.task_id // "NOT_OBSERVED"),project_id:(.project_id // "NOT_OBSERVED"),
             status:(.status // "NOT_OBSERVED"),assigned_to:(.assigned_to // "NOT_OBSERVED"),
             assigned_at:(.assigned_at // "NOT_OBSERVED"),result_status:(.result_status // "NOT_OBSERVED"),
             acknowledged_by_role:(.acknowledged_by_role // "NOT_OBSERVED"),submitted_by_role:(.submitted_by_role // "NOT_OBSERVED"),
             room_id:(.room_id // "NOT_OBSERVED"),source_room_id:(.source_room_id // "NOT_OBSERVED"),
             event_id:(.eventId // .notification.eventId // "NOT_OBSERVED"),result_path:(.result_path // "NOT_OBSERVED")}' >>"$out/task-metadata.jsonl" || true
      fi
    done <"$paths"
  done
  [[ -s "$out/task-artifacts.jsonl" ]] || note_missing "shared_fs.task_artifacts"
}

capture_pg() {
  local out=$1
  if [[ "$PG_CONTAINER" == NONE ]]; then printf '{"status":"NOT_OBSERVED","reason":"disabled"}\n' >"$out"; note_missing pg.tw_rows; return; fi
  : >"$out"
  tables=$(docker exec "$PG_CONTAINER" psql -XAt -U "$PG_USER" -d "$PG_DB" -c \
    "select tablename from pg_tables where schemaname='public' and tablename like 'tw\\_%' escape '\\' order by 1" 2>/dev/null || true)
  [[ -n "$tables" ]] || { printf '{"status":"NOT_OBSERVED"}\n' >"$out"; note_missing pg.tw_rows; return; }
  while IFS= read -r table; do
    [[ "$table" =~ ^tw_[a-zA-Z0-9_]+$ ]] || continue
    columns=$(docker exec "$PG_CONTAINER" psql -XAt -U "$PG_USER" -d "$PG_DB" -c \
      "select column_name from information_schema.columns where table_schema='public' and table_name='$table' and column_name in ('run_id','campaign_id') order by 1" 2>/dev/null || true)
    where=''
    if grep -qx campaign_id <<<"$columns"; then where="campaign_id='$CAMPAIGN_ID'"; fi
    if grep -qx run_id <<<"$columns"; then
      [[ -n "$where" ]] && where="$where and "
      where="${where}run_id='$RUN_ID'"
    fi
    if [[ -z "$where" ]]; then note_missing "pg.unscoped_table.$table"; continue; fi
    if ! docker exec "$PG_CONTAINER" psql -XAt -U "$PG_USER" -d "$PG_DB" -c \
      "select row_to_json(t)::text from public.\"$table\" t where $where" 2>/dev/null |
      python3 -c 'import hashlib,json,sys
table=sys.argv[1]
for raw in sys.stdin.buffer:
 raw=raw.rstrip(b"\n")
 if raw: print(json.dumps({"table":table,"row_hash":hashlib.sha256(raw).hexdigest()},sort_keys=True))' "$table" >>"$out"; then
      note_missing "pg.read.$table"
    fi
  done <<<"$tables"
  [[ -s "$out" ]] || { printf '{"status":"NOT_OBSERVED"}\n' >"$out"; note_missing pg.tw_rows; }
}

snapshot() {
  local stamp
  stamp=$(utc_stamp)
  SNAPSHOT_DIR="$EVIDENCE_DIR/snapshots/$stamp"
  mkdir -p "$SNAPSHOT_DIR" "$SNAPSHOT_DIR/authority" "$SNAPSHOT_DIR/matrix" "$SNAPSHOT_DIR/containers" "$SNAPSHOT_DIR/skills" "$SNAPSHOT_DIR/sessions"
  : >"$SNAPSHOT_DIR/not-observed.tsv"
  for resource in managers teams workers projects; do
    if ! agt_json "$resource" "$SNAPSHOT_DIR/authority/$resource.json"; then
      printf '{"status":"NOT_OBSERVED"}\n' >"$SNAPSHOT_DIR/authority/$resource.json"; note_missing "agt.$resource"
    fi
  done
  if ! build_roster "$SNAPSHOT_DIR/authority/managers.json" "$SNAPSHOT_DIR/authority/teams.json" "$SNAPSHOT_DIR/authority/workers.json" "$SNAPSHOT_DIR/roster.json"; then
    die "the selected two-Team topology is not readable from agt"
  fi
  resolve_containers "$SNAPSHOT_DIR/roster.json" "$SNAPSHOT_DIR/containers.tsv"
  ensure_log_followers "$SNAPSHOT_DIR/containers.tsv"
  while IFS=$'\t' read -r actor container; do
    [[ -n "$actor" ]] || continue
    kind=$(jq -r --arg n "$actor" '.actors[] | select(.name==$n) | .kind' "$SNAPSHOT_DIR/roster.json")
    matrix_id=$(jq -r --arg n "$actor" '.actors[] | select(.name==$n) | .matrix_user_id // "NOT_OBSERVED"' "$SNAPSHOT_DIR/roster.json")
    key=$(safe_name "$actor")
    capture_container "$actor" "$container" "$SNAPSHOT_DIR/containers/$key.json"
    capture_skills "$actor" "$container" "$SNAPSHOT_DIR/skills/$key"
    capture_sessions "$actor" "$kind" "$container" "$SNAPSHOT_DIR/sessions/$key"
    capture_matrix_actor "$actor" "$kind" "$container" "$matrix_id" "$SNAPSHOT_DIR/matrix/$key"
  done <"$SNAPSHOT_DIR/containers.tsv"
  manager_name=$(jq -r '.actors[] | select(.kind=="manager") | .name' "$SNAPSHOT_DIR/roster.json" | head -1)
  manager_session=''
  if [[ -n "$manager_name" ]]; then manager_session="$SNAPSHOT_DIR/sessions/$(safe_name "$manager_name")/readback.jsonl"; fi
  [[ -f "$manager_session" ]] || manager_session=''
  if [[ -n "$manager_session" ]]; then
    jq -s '([.[]|select(.role=="user")|.record_hash]) as $requests |
      ([.[]|select(.role=="assistant")|.record_hash]) as $responses |
      {status:(if any(.[]; .role=="assistant" and .provider!=null and .model!=null) then "OBSERVED_PROVIDER_TURN" else "NOT_OBSERVED" end),
      provider_models:[.[]|select(.role=="assistant")|{provider:(.provider//"NOT_OBSERVED"),model:(.model//"NOT_OBSERVED"),usage:(.usage//"NOT_OBSERVED"),latency_ms:(.latency_ms//"NOT_OBSERVED")}]|unique,
      request_hash:($requests[-1]//"NOT_OBSERVED"),response_hash:($responses[-1]//"NOT_OBSERVED"),
      request_hashes:$requests,response_hashes:$responses,scope_mentions:[.[]|.scope_mentions]|unique,
      caveat:"Hashes prove native session records; semantic Manager choice requires correlation with exact Matrix events."}' "$manager_session" >"$SNAPSHOT_DIR/manager-choice-readback.json"
  else
    printf '{"status":"NOT_OBSERVED"}\n' >"$SNAPSHOT_DIR/manager-choice-readback.json"
    note_missing manager_choice.session
  fi
  capture_shared_files "$SNAPSHOT_DIR/roster.json" "$SNAPSHOT_DIR/containers.tsv" "$SNAPSHOT_DIR/shared-fs"
  if [[ -s "$SNAPSHOT_DIR/shared-fs/task-metadata.jsonl" ]]; then
    jq -s '{source:"native TeamHarness shared task metadata",tasks:.}' "$SNAPSHOT_DIR/shared-fs/task-metadata.jsonl" >"$SNAPSHOT_DIR/authority/tasks.json"
  else
    printf '{"source":"native TeamHarness shared task metadata","status":"NOT_OBSERVED","tasks":[]}\n' >"$SNAPSHOT_DIR/authority/tasks.json"
  fi
  capture_pg "$SNAPSHOT_DIR/pg-tw-row-hashes.jsonl"
  jq -n --arg schema testweaver.native-hero-capture.v1 --arg captured_at "$(utc_now)" \
    --arg campaign_id "$CAMPAIGN_ID" --arg run_id "$RUN_ID" --arg trace_id "$TRACE_ID" \
    --arg boundary_utc "$BOUNDARY_UTC" --arg allowlist_sha256 "$HUMAN_ALLOWLIST_SHA256" \
    --arg snapshot_ref "${SNAPSHOT_DIR#"$EVIDENCE_DIR"/}" --slurpfile roster "$SNAPSHOT_DIR/roster.json" \
    '{schema:$schema,captured_at:$captured_at,authority_scope:{campaign_id:$campaign_id,run_id:$run_id,trace_id:$trace_id},
      boundary_utc:$boundary_utc,target_topology:$roster[0],human_identity:{binding:"HOMESERVER_EXACT_GET_PLUS_PROTECTED_ALLOWLIST",allowlist_sha256:$allowlist_sha256},
      immutable_source_policy:{matrix:"exact GET response raw-bytes SHA-256",sessions:"container session-file SHA-256 plus record SHA-256",resources:"agt readback",normalized_records_must_reference_source:true},
      manager_choice_fields:{provider:"READ_FROM_SESSION_OR_NOT_OBSERVED",model:"READ_FROM_SESSION_OR_NOT_OBSERVED",latency:"READ_FROM_SESSION_OR_NOT_OBSERVED",usage:"READ_FROM_SESSION_OR_NOT_OBSERVED",request_hash:"user record_hash or NOT_OBSERVED",response_hash:"assistant record_hash or NOT_OBSERVED"},
      writes:{matrix:false,agentteams_resources:false,provider:false,faults:false,database:false,evidence:true},classification:"NOT_ASSESSED",live_claimed:false,snapshot_ref:$snapshot_ref}' >"$SNAPSHOT_DIR/snapshot-manifest.json"
  ln -sfn "snapshots/$stamp" "$EVIDENCE_DIR/latest"
  update_manifest ACTIVE PROVISIONAL "$stamp"
  write_sums
}

update_manifest() {
  local status=$1 checksum_state=$2 latest=$3
  jq -n --arg schema testweaver.native-hero-capture.v1 --arg status "$status" --arg checksum_state "$checksum_state" \
    --arg campaign_id "$CAMPAIGN_ID" --arg run_id "$RUN_ID" --arg trace_id "$TRACE_ID" \
    --arg boundary_utc "$BOUNDARY_UTC" --arg latest_snapshot "snapshots/$latest" \
    --arg allowlist_sha256 "$HUMAN_ALLOWLIST_SHA256" --arg t1 "${TEAMS[0]}" --arg t2 "${TEAMS[1]}" '
      {schema:$schema,status:$status,authority_scope:{campaign_id:$campaign_id,run_id:$run_id,trace_id:$trace_id},
       boundary_utc:$boundary_utc,target_teams:[$t1,$t2],latest_snapshot:$latest_snapshot,
       human_allowlist_sha256:$allowlist_sha256,checksum_state:$checksum_state,
       classification:"NOT_ASSESSED",live_claimed:false,
       prohibited_actions_performed:{matrix_send:false,resource_mutation:false,fault_injection:false,provider_call:false,gold_read:false,event_injection:false}}' >"$EVIDENCE_DIR/manifest.json"
}

write_sums() {
  local sums_tmp="$STATE_DIR/SHA256SUMS.tmp"
  (
    cd "$EVIDENCE_DIR"
    find . -type f ! -path './.state/*' ! -name SHA256SUMS -print0 | sort -z | xargs -0 -r sha256sum >"$sums_tmp"
    mv "$sums_tmp" SHA256SUMS
  )
}

case "$COMMAND" in
  start)
    if [[ -e "$EVIDENCE_DIR" ]] && [[ -n "$(find "$EVIDENCE_DIR" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)" ]]; then
      die "evidence directory already exists and is not empty"
    fi
    mkdir -p "$EVIDENCE_DIR"
    write_config
    # shellcheck disable=SC1090
    source "$CONFIG"
    snapshot
    ;;
  snapshot)
    load_config
    snapshot
    ;;
  stop)
    load_config
    snapshot
    if [[ -f "$STATE_DIR/collectors.tsv" ]]; then
      while IFS=$'\t' read -r pid _; do
        [[ "$pid" =~ ^[0-9]+$ ]] || continue
        pkill -TERM -P "$pid" 2>/dev/null || true
        kill "$pid" 2>/dev/null || true
        wait "$pid" 2>/dev/null || true
      done <"$STATE_DIR/collectors.tsv"
    fi
    latest=$(basename "$(readlink "$EVIDENCE_DIR/latest")")
    update_manifest STOPPED FINAL "$latest"
    write_sums
    ;;
esac
